
/**************************************************************
 *	
 *	cheer, 8 bit, 11025Hz,
 *	1 channel, 59490 bytes/channel
 *	Total Size: 1 * 59490 + 4 (header) = 59534 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/hyunjoochoi/Desktop/School/CS 2261 Milestones/M4/cheer.wav
 *	Time-stamp: Fri Apr 26 02:46:43 2019
 *	
 **************************************************************/

#ifndef __CHEERH__
#define __CHEERH__

#define CHEERFREQ 11025
#define CHEERLEN 59490

extern const unsigned char cheer[59490];

#endif /* __CHEERH__ */
