
/**************************************************************
 *	
 *	hit, 8 bit, 11025Hz,
 *	1 channel, 5449 bytes/channel
 *	Total Size: 1 * 5449 + 4 (header) = 5493 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/hyunjoochoi/Desktop/School/CS 2261 Milestones/M4/hit.wav
 *	Time-stamp: Fri Apr 26 02:31:42 2019
 *	
 **************************************************************/

#ifndef __HITH__
#define __HITH__

#define HITFREQ 11025
#define HITLEN 5449

extern const unsigned char hit[5449];

#endif /* __HITH__ */
