
/**************************************************************
 *	
 *	playerhit, 8 bit, 11025Hz,
 *	1 channel, 7451 bytes/channel
 *	Total Size: 1 * 7451 + 4 (header) = 7495 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/hyunjoochoi/Desktop/School/CS 2261 Milestones/M4/playerhit.wav
 *	Time-stamp: Fri Apr 26 02:36:54 2019
 *	
 **************************************************************/

#ifndef __PLAYERHITH__
#define __PLAYERHITH__

#define PLAYERHITFREQ 11025
#define PLAYERHITLEN 7451

extern const unsigned char playerhit[7451];

#endif /* __PLAYERHITH__ */
