
/**************************************************************
 *	
 *	shoot, 8 bit, 11025Hz,
 *	1 channel, 5513 bytes/channel
 *	Total Size: 1 * 5513 + 4 (header) = 5557 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/hyunjoochoi/Desktop/School/CS 2261 Milestones/M4/shoot.wav
 *	Time-stamp: Thu Apr 18 18:42:47 2019
 *	
 **************************************************************/

#ifndef __SHOOTH__
#define __SHOOTH__

#define SHOOTFREQ 11025
#define SHOOTLEN 5513

extern const unsigned char shoot[5513];

#endif /* __SHOOTH__ */
