
/**************************************************************
 *	
 *	thecarnival, 8 bit, 11025Hz,
 *	1 channel, 1571328 bytes/channel
 *	Total Size: 1 * 1571328 + 4 (header) = 1571372 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/hyunjoochoi/Desktop/School/CS 2261 Milestones/M4/thecarnival.wav
 *	Time-stamp: Thu Apr 18 18:15:18 2019
 *	
 **************************************************************/

#ifndef __THECARNIVALH__
#define __THECARNIVALH__

#define THECARNIVALFREQ 11025
#define THECARNIVALLEN 1571328

extern const unsigned char thecarnival[1571328];

#endif /* __THECARNIVALH__ */
